### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SimonKitSangChu** [DeepRank/PSSMGen#15]
SyntaxError when importing PSSM

```
from pssmgen import PSSM
Traceback (most recent call last):

  File "/share/siegellab/software/kschu/anaconda3/envs/work/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-8c86748574e6>", line 1, in <module>
    from pssmgen import PSSM

  File "/share/siegellab/software/kschu/anaconda3/envs/work/lib/python3.5/site-packages/pssmgen/__init__.py", line 1, in <module>
    from .pssm import PSSM

  File "/share/siegellab/software/kschu/anaconda3/envs/work/lib/python3.5/site-packages/pssmgen/pssm.py", line 92
    logger.info(f'  {fname}')
                           ^
SyntaxError: invalid syntax

```

**Comment by SimonKitSangChu** [comment]
Upgrade to python 3.6 formatting.
