### ISSUE TITLE
Lack examine of pssm output files of each iteration

### ISSUE THREAD

**Issue by CunliangGeng** [DeepRank/PSSMGen#6]
**Describe the bug**
The  #iterations of psiblast is 3 by default. But it could converge before the 3rd iteration, thus giving only one or two output pssm files. The code did not check the existence of output pssm files and directly use the 3rd iteration pssm file which cause the `FileNotFoundError`.

**Actual Results or Error Info**

```
Traceback (most recent call last):
  File "run_pssmgen_5hy3.py", line 21, in <module>
    gen.get_pssm(fasta_dir='fasta', out_dir='pssm_raw', run=True)
  File "/home/fmeiman/software/anaconda3/lib/python3.7/site-packages/pssmgen/pssm.py", line 207, in get_pssm
    shutil.copy2(out_ascii_pssm + '.%d' %self.blast_config['num_iterations'], out_ascii_pssm)
  File "/home/fmeiman/software/anaconda3/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/fmeiman/software/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '5hy3/pssm_raw/5hy3.B.pssm.3'
```

**Comment by CunliangGeng** [comment]
Done in commit f8cc57111565c5d743caa0e9d01f4327fa3cb471.
